# image
image: Visual Studio 2017

# build platform
platform: x64

# clone directory
clone_folder: c:\aeon-stak-cpu

install:
  - mkdir c:\aeon-stak-dep
  - curl -sL https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip -o aeon-stak-dep.zip
  - 7z x aeon-stak-dep.zip -o"c:\aeon-stak-dep" -y > nul

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\aeon-stak-cpu
  - mkdir build
  - cd build
  - set CMAKE_PREFIX_PATH=C:\aeon-stak-dep\hwloc;C:\aeon-stak-dep\libmicrohttpd;C:\aeon-stak-dep\openssl;
  - cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
  - msbuild aeon-stak-cpu.sln /p:Configuration=Release

test_script:
  - cd c:\aeon-stak-cpu\build\bin\Release
  - dir
  - copy ..\..\..\config.txt .
#  - aeon-stak-cpu.exe
